server:
  port: 8095
  servlet:
    context-path: /infovision
spring:
  application:
    name: infovision-canteen-service
  datasource:
    url: jdbc:postgresql://flexibleserver10.postgres.database.azure.com:5432/Canteen?createDatabaseIfNotExist=true
    username: Server
    password: Password@123
    driver-class-name: org.postgresql.Driver

  jpa: 
    generate-ddl: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    main:
      web-application-type: none

swagger:
  url: https://info.eat/infovision

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    instance:
    hostname: localhost



